CREATE TABLE TB_CUSTOMER (
    ID_CUSTOMER INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    CPF VARCHAR(14)
    
);

CREATE TABLE TB_PRODUCT (
    ID_PRODUCT INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    PRICE NUMERIC(20, 2)
);

CREATE TABLE TB_ORDER (
    ID_ORDER INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CUSTOMER INTEGER REFERENCES TB_CUSTOMER (ID_CUSTOMER),
    ORDER_DATE TIMESTAMP,
    ORDER_STATUS VARCHAR(50),
    TOTAL NUMERIC (20, 2)
);


CREATE TABLE TB_ORDER_ITEM (
    ID_ORDER_ITEM INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_ORDER INTEGER REFERENCES TB_ORDER (ID_ORDER),
    ID_PRODUCT INTEGER REFERENCES TB_PRODUCT (ID_PRODUCT),
    QUANTITY INTEGER
);

CREATE TABLE TB_USER (
    ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255)NOT NULL,
    ADMIN BOOL DEFAULT FALSE
    
);


